In [ ]:
#Andrew Salcedo
#Homework 3, Plot functions
# 9/13/26

In [81]:
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
from astropy.io import fits
import hw3_asalcedo_support_functions as hw3_supp_funcs

In [98]:
test_square_1 = np.arange(0,9)
print(f"test square 1:\n{test_square_1}")
print("result 1:\n", hw3_supp_funcs.square(test_square_1))

test_square_2 = np.arange(0.0,25.0).reshape(5,5)
print(f"\ntest square 2:\n{test_square_2}")
print("\nresult 2:\n", hw3_supp_funcs.square(test_square_2))

test square 1:
[0 1 2 3 4 5 6 7 8]
result 1:
 [ 0  1  4  9 16 25 36 49 64]

test square 2:
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]

result 2:
 [[  0.   1.   4.   9.  16.]
 [ 25.  36.  49.  64.  81.]
 [100. 121. 144. 169. 196.]
 [225. 256. 289. 324. 361.]
 [400. 441. 484. 529. 576.]]
